### ISSUE TITLE
AttributeError: 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by QUANmoxiansheng** [TIM2015YXH/HaveFun#3]
AttributeError: 'str' object has no attribute 'decode'

**Comment by QUANmoxiansheng** [comment]
(havefun) lc@lc-NF5468M6:/mnt/sdb1/qm/HaveFun$ bash ./scripts/body_experiments/train.sh FS-Humans 019 male 4view 0.01
-----Start Training---------
dataset: FS-Humans
identity: 019
gender: male
Number of view: 4view
lambda_guidance: 0.01
image_config: config/FS-Humans/019/4view_camera_rotate.csv
workspace: out/FS-Humans/019/camera_rotate_tpose_4view
Maximum iters: 17500
Warning:
Unable to load the following plugins:

        libio_e57.so: libio_e57.so does not seem to be a Qt Plugin.

Cannot load library /home/lc/miniconda3/envs/havefun/lib/python3.9/site-packages/pymeshlab/lib/plugins/libio_e57.so: (/lib/x86_64-linux-gnu/libp11-kit.so.0: undefined symbol: ffi_type_pointer, version LIBFFI_BASE_7.0)

Namespace(file=None, text=None, negative='', O=True, O2=False, test=False, six_views=False, eval_interval=5, test_interval=25, workspace='out/FS-Humans/019/camera_rotate_tpose_4view', seed=None, image=None, image_config='config/FS-Humans/019/4view_camera_rotate.csv', known_view_interval=4, IF=False, guidance=['zero123'], guidance_scale=5, freeze_guidance=False, save_mesh=True, mcubes_resolution=256, decimate_target=50000.0, dmtet=True, tet_grid_size=128, init_with='$./{data_dir}/FS-Humans/training/019/smplx/tpose.obj', lock_geo=False, perpneg=False, negative_w=-2, front_decay_factor=2, side_decay_factor=10, iters=17500, lr=0.001, lr_iters=2500, ckpt='latest', cuda_ray=True, max_steps=1024, num_steps=64, upsample_steps=32, update_extra_interval=16, max_ray_batch=4096, latent_iter_ratio=0, albedo_iter_ratio=0, min_ambient_ratio=0.1, textureless_ratio=0.2, jitter_pose=False, jitter_center=0.2, jitter_target=0.2, jitter_up=0.02, uniform_sphere_rate=0, grad_clip=-1, grad_clip_rgb=-1, head_recon=2.0, hand_recon=2.0, bg_radius=0.0, density_activation='exp', density_thresh=10, blob_density=5, blob_radius=0.2, backbone='grid', optim='adan', sd_version='2.1', hf_key=None, uvd_proj=False, pose_path=None, gt_smplx='data/FS-Humans/training/019/smplx/tpose.pkl', handy_path=None, smplx_path='models/smplx', gender='male', flat_hand_mean=False, mano_path=None, eval_metrics=False, eval_supl=False, hand_dst_shape=None, real_shape_scale=None, various_pose=True, tpose=True, hand_tpose=False, mesh_rotate=False, expression=True, tets=None, denormalize=False, oneviewloss=False, real_hand_pose=False, fp16=True, vram_O=False, w=512, h=512, known_view_scale=1, known_view_noise_scale=0.002, dmtet_reso_scale=8, batch_size=1, bound=1, dt_gamma=0, min_near=0.01, radius_range=[3.0, 3.5], theta_range=[0, 180], phi_range=[-180, 180], fovy_range=[20, 20], default_radius=3.2, default_polar=90, default_azimuth=0, default_fovy=20, progressive_view=False, progressive_view_init_ratio=0.2, progressive_level=True, angle_overhead=30, angle_front=60, t_range=[0.02, 0.5], dont_override_stuff=False, view_angle=0, lambda_entropy=1, lambda_opacity=0, lambda_orient=1, lambda_tv=0, lambda_wd=0, lambda_mesh_normal=0.5, lambda_mesh_laplacian=0.5, lambda_guidance=0.01, lambda_rgb=100.0, lambda_mask=1000.0, lambda_normal=50.0, lambda_depth=50.0, lambda_2d_normal_smooth=0, lambda_3d_normal_smooth=10, lambda_normal_sds=0, lap_vn=False, lambda_sds=1, const_ambient_ratio=1.0, real_mesh_scale_path=None, save_guidance=False, save_guidance_interval=10, gui=False, W=800, H=800, radius=5, fovy=20, light_theta=60, light_phi=0, max_spp=1, zero123_config='pretrained/zero123/sd-objaverse-finetune-c_concat-256.yaml', zero123_ckpt='pretrained_dfmodel/zero123/zero123-xl.ckpt', zero123_grad_scale='angle', dataset_size_train=100, dataset_size_valid=8, dataset_size_test=100, exp_start_iter=0, exp_end_iter=17500, images=['data/FS-Humans/training/019/basecolor/0.png', 'data/FS-Humans/training/019/basecolor/7.png', 'data/FS-Humans/training/019/basecolor/4.png', 'data/FS-Humans/training/019/basecolor/1.png'], ref_radii=[3.2, 3.2, 3.2, 3.2], ref_polars=[90, 90, 90, 90], ref_azimuths=[0, 45, -180, -45], zero123_ws=[1, 1, 1, 1], default_zero123_w=1)
Traceback (most recent call last):
  File "/mnt/sdb1/qm/HaveFun/main.py", line 368, in <module>
    mesh = trimesh.load(opt.init_with, force='mesh', skip_material=True, process=False)
  File "/home/lc/miniconda3/envs/havefun/lib/python3.9/site-packages/trimesh/exchange/load.py", line 126, in load
    loaded = load_mesh(file_obj, file_type=file_type, resolver=resolver, **kwargs)
  File "/home/lc/miniconda3/envs/havefun/lib/python3.9/site-packages/trimesh/exchange/load.py", line 202, in load_mesh
    results = loader(file_obj, file_type=file_type, resolver=resolver, **kwargs)
  File "/home/lc/miniconda3/envs/havefun/lib/python3.9/site-packages/trimesh/exchange/misc.py", line 41, in load_dict
    data = json.loads(data.decode("utf-8"))
AttributeError: 'str' object has no attribute 'decode'
